### ISSUE TITLE
About aerospike and aerospike-server

### ISSUE THREAD

**Issue by felixsanz** [aerospike/aerospike-server.docker#12]
Whats the reason for having 2 docker images for the same thing? Or they are not equally? If so, what are the differences?

I know one is automated but that shouldn't be a reason for having a duplicated/confusing docker image in my opinnion.

https://hub.docker.com/_/aerospike/
https://hub.docker.com/r/aerospike/aerospike-server/

**Comment by volmarl** [comment]
They are both the same. Aerospike-server was the original repo prior to aerospike getting reviewed and approved for Docker Officlal Repo. 
In more specific term,  the /aerospike image is the official repo scanned and blessed by Docker.
aerospike-server is the original public repo build. We will work on deprecating the non-official version.
