### ISSUE TITLE
Unknown config parameter mesh-port when starting container

### ISSUE THREAD

**Issue by y0ssar1an** [aerospike/aerospike-server.docker#13]
```
$ docker run --name test -P aerospike
Aug 23 2016 21:59:07 GMT: CRITICAL (config): (cfg.c:1309) line 48 :: unknown config parameter name 'mesh-port'
Aug 23 2016 21:59:07 GMT: WARNING (as): (signal.c:153) SIGINT received, shutting down
Aug 23 2016 21:59:07 GMT: WARNING (as): (signal.c:156) startup was not complete, exiting immediately
```
I'm using Docker for Mac 1.12.0-a on OS X El Capitan.

**Comment by volmarl** [comment]
Could you let us know which version (tag) of the container are you using? and possibly post your aerospike.conf

**Comment by y0ssar1an** [comment]
The tag is `latest`. The `aerospike` config is the default config is.

**Comment by volmarl** [comment]
Thanks. I fixed the issue on the issue with the default config. Were you using github and building it from scratch or Docker Hub?

**Comment by y0ssar1an** [comment]
Docker Hub

**Comment by volmarl** [comment]
Official repo update may take a couple of days. In the mean time, you could overwrite default config and remove mesh-port line in aerospike.conf

**Comment by volmarl** [comment]
Fix is now available on official immage in docker hub.

https://hub.docker.com/_/aerospike/
