### ISSUE TITLE
Aerospike Forums link broken in README

### ISSUE THREAD

**Issue by y0ssar1an** [aerospike/aerospike-server.docker#14]
The link to the Aerospike Forums in the README is broken. I was hoping to report that the aerospike container is currently [completely broken for me](https://github.com/aerospike/aerospike-server.docker/issues/13).

**Comment by mtendjou** [comment]
Thanks for reporting this. It should be fixed now.

**Comment by y0ssar1an** [comment]
Thanks! Can I get a comment on the currently released official Docker Hub image being completely broken. Are you aware of the issue?
