### ISSUE TITLE
Tagging

### ISSUE THREAD

**Issue by felixsanz** [aerospike/aerospike-server.docker#20]
It is possible to have correct tagging for aerospike releases?

Currently there is only possible to install `3.10.1.1` or `latest`. What about `3`, `3.10` and `3.10.1` ? The first two would be useful.

Also are you aware of the vulnerabilities showed here? https://hub.docker.com/r/library/aerospike/tags/latest/

**Comment by volmarl** [comment]
Thanks for the feedback. We try to only keep the current stable version on the official release.

older versions are available in our github repo.

We are using the xenial base OS. Let me see if any additional patching is available.
