### ISSUE TITLE
Alpine based image

### ISSUE THREAD

**Issue by huydinhle** [aerospike/aerospike-server.docker#23]
Can we have an alpine based image for Aerospike. 

I tried to follow this guide http://www.aerospike.com/docs/operations/install/linux/other to install aerospike in Alpine with glibc but it didn't work

**Comment by volmarl** [comment]
Let us research this and figure out if our glibc requirement will work on Alpine.

**Comment by scippio** [comment]
Any news in this?

**Comment by volmarl** [comment]
Currently Experimenting with https://hub.docker.com/r/frolvlad/alpine-glibc/ 
No official support for Alpine at present time.

**Comment by scippio** [comment]
:disappointed: ok.. thanks for answer.

**Comment by devrck** [comment]
Can you foresee a docker image running alpine linux with aerospike in the near future?
