### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by prasad9306** [aerospike/aerospike-server.docker#34]
I am trying to build Aerospike-Server using Docker. Here the docker base image is ubuntu: bionic but am in need of an Alpine version of Docker file. Please let me know if there is any aerospike official repository or an alternative approach for this.

**Comment by volmarl** [comment]
Our base image is now debian9.5-slim which should be more secured and have less of a footprint.
As of now we don't have an Alpine Docker or install procedure. We will further look into this internally.
