### ISSUE TITLE
cli client not included in container

### ISSUE THREAD

**Issue by dnelson** [aerospike/aerospike-server.docker#4]
I was trying to write basic functionality tests for https://github.com/docker-library/official-images/issues/586 but was unable to access the database via the docker container because the tools that are mentioned in the documentation does not appear to be included in the Docker container.

Can the cli client be added to the container?

**Comment by volmarl** [comment]
We had deliberately removed the tools from the container to create a lighter container. We were planning to create a seperate container for tools. Would a seperate container for tools help you with your test case? Or would you need to have it on the same container?

**Comment by cstivers78** [comment]
We will release a aerospike-tools container, which you can use to run one of our many tools.

**Comment by packetcollision** [comment]
I don't think any of the existing Docker official-image tests require a secondary container, but maybe @tianon can shed light on whether that is an acceptable way to run the tests.

**Comment by fattenap** [comment]
+1 aerospike-tools container :+1:

**Comment by tianon** [comment]
Here's one that currently uses separate containers to run the MySQL daemon
and the MySQL client:
https://github.com/docker-library/official-images/blob/ac172614c20881939886780512eb12ecbf352850/test/tests/mysql-basics/run.sh

What I suspect you meant was a separate image, for which the following is a
good example: (it builds a second image specifically to get the "cgi-fcgi"
client binary)
https://github.com/docker-library/official-images/blob/ac172614c20881939886780512eb12ecbf352850/test/tests/php-fpm-hello-web/run.sh

**Comment by tclass** [comment]
yepp, aerospike-tools container would be great, any update on this?

**Comment by volmarl** [comment]
We're trying to have it deployed this week.

**Comment by volmarl** [comment]
Aerospike Tools container is now deployed:
https://github.com/aerospike/aerospike-tools.docker

**Comment by tclass** [comment]
@volmarl: wow that was fast, thx :)
