### ISSUE TITLE
Can not start-up the docker with the access-address, version 3.5.4

### ISSUE THREAD

**Issue by onokonem** [aerospike/aerospike-server.docker#5]
Hi

this is exactly the same as #1 , but with different aerospike version

```
Apr 04 2015 23:50:41 GMT: CRITICAL (info): (thr_info.c:info_interfaces_static_fn:5074) external address:10.243.40.132 is not matching with any of service addresses:172.17.0.6:3000
```

any suggestions?

Thank you

**Comment by mtendjou** [comment]
As of version 3.3.26, you can solve this by adding the keyword 'virtual' after the access-address, if the access-address is not matching any physical address, for example:

service {
                address any
                port 3000

                access-address 10.243.40.132 virtual
        }

**Comment by onokonem** [comment]
no, the `virtual` keyword does not work for me

**Comment by mtendjou** [comment]
Which version are you using?

**Comment by onokonem** [comment]
3.5.4

**Comment by mtendjou** [comment]
Could you paste your configuration file? (you can mask IP addresses or anything that may be sensitive, just want to double check if everything is correct).

**Comment by onokonem** [comment]
https://github.com/gitinsky/aerospike-server.docker/blob/master/etc/aerospike/aerospike.conf.template

**Comment by mtendjou** [comment]
Thanks for the input.

```
network {
  service {
    port 3000
    access-address <%=os.getenv("NODE_EXT_ADDR")%> virtual
  }

  fabric {
    port 3001
    access-address <%=os.getenv("NODE_INT_ADDR")%> virtual
  }
```

I am pretty sure that access-address in the fabric sub-stanza is not supported. The default there should be `address any`. 

Also, under the service sub-stanza, you should have `address any` (am not sure if it will default if not specified at all like in your example). I will try to provide you with more details but this may be what's causing this error in the log (haven't got a chance to try to reproduce yet though).

**Comment by mtendjou** [comment]
Any luck? We checked in the code and it really seems pretty straight forward that this error message  message `CRITICAL (info): (thr_info.c:info_interfaces_static_fn:5074) external address:10.243.40.132 is not matching with any of service addresses:172.17.0.6:3000` would only show up if the address really didn't match or if the `virtual` keyword is not added right. 

Can you try by adding IP address instead of the os.getenv and removing the access address from the fabric sub-stanza? 

Thanks.

**Comment by ArtworkAD** [comment]
Just checked this with the recent version and it worked for me without a problem.

**Comment by onokonem** [comment]
Great!
