### ISSUE TITLE
"latest" docker tag missing

### ISSUE THREAD

**Issue by AlexanderVagner** [aerospike/aerospike-server.docker#52]
The `latest` tag is currently [missing](https://hub.docker.com/r/aerospike/aerospike-server/tags?page=1&ordering=last_updated&name=latest) from the docker repository, please add this tag back.

```
(base) ➜  ~ docker pull aerospike/aerospike-server
Using default tag: latest
Error response from daemon: manifest for aerospike/aerospike-server:latest not found: manifest unknown: manifest unknown
```

**Comment by kportertx** [comment]
Thank you, this has been resolved.
